model:
  best_model: XGBoost
  feature_sets:
    rfe:
    - state_Alabama
    - state_Arizona
    - state_Arkansas
    - state_California
    - state_Colorado
    - state_Florida
    - state_Georgia
    - state_Illinois
    - state_Indiana
    - state_Kansas
    - state_Kentucky
    - state_Louisiana
    - state_Maryland
    - state_Michigan
    - state_Mississippi
    - state_Missouri
    - state_Nebraska
    - state_NewJersey
    - state_NewYork
    - state_NorthCarolina
    - state_Ohio
    - state_Oklahoma
    - state_Pennsylvania
    - state_SouthCarolina
    - state_Tennessee
    - state_Texas
    - state_Virginia
    - state_Washington
    - state_WestVirginia
    - source_type_coal
    - source_type_gas
    - source_type_oil
    - inter_Arizona_coal
    - inter_Arizona_gas
    - inter_Arkansas_coal
    - inter_Arkansas_gas
    - inter_Colorado_coal
    - inter_Connecticut_coal
    - inter_Connecticut_gas
    - inter_Florida_coal
    - inter_Florida_gas
    - inter_Florida_oil
    - inter_Georgia_coal
    - inter_Georgia_gas
    - inter_Illinois_gas
    - inter_Indiana_coal
    - inter_Indiana_gas
    - inter_Kansas_gas
    - inter_Kentucky_coal
    - inter_Kentucky_gas
    - inter_Louisiana_coal
    - inter_Louisiana_gas
    - inter_Maryland_coal
    - inter_Maryland_oil
    - inter_Michigan_coal
    - inter_Michigan_gas
    - inter_Mississippi_coal
    - inter_Mississippi_gas
    - inter_Missouri_coal
    - inter_Missouri_gas
    - inter_Missouri_oil
    - inter_Nevada_gas
    - inter_NewMexico_coal
    - inter_NewYork_gas
    - inter_NorthCarolina_coal
    - inter_NorthDakota_gas
    - inter_Ohio_gas
    - inter_Ohio_oil
    - inter_Oklahoma_coal
    - inter_Oklahoma_gas
    - inter_Oklahoma_oil
    - inter_Oregon_gas
    - inter_Pennsylvania_coal
    - inter_Pennsylvania_gas
    - inter_Pennsylvania_oil
    - inter_SouthCarolina_coal
    - inter_Tennessee_coal
    - inter_Tennessee_gas
    - inter_Texas_coal
    - inter_Texas_gas
    - inter_Texas_oil
    - inter_Virginia_coal
    - inter_Washington_coal
    - inter_Washington_gas
    - capacity
    - capacity_factor
    - activity
    - area
    - pop2020
    - log1Pop_density
    - activity_per_capita
    - activity_per_area
    - capacity_per_capita
    - capacity_density
    - potential_output
    - utilization_ratio
    - activity_capacityFactor
    - activity_per_capacity
    - activity_capacity
    - capacity_factor_capacity
  mae: 39043.82364412297
  name: greenhouse_emission_predict_model
  parameters:
    base_score: null
    booster: null
    callbacks: null
    colsample_bylevel: null
    colsample_bynode: null
    colsample_bytree: null
    device: null
    early_stopping_rounds: null
    enable_categorical: false
    eval_metric: null
    feature_types: null
    feature_weights: null
    gamma: null
    grow_policy: null
    importance_type: null
    interaction_constraints: null
    learning_rate: 0.1
    max_bin: null
    max_cat_threshold: null
    max_cat_to_onehot: null
    max_delta_step: null
    max_depth: 20
    max_leaves: null
    min_child_weight: null
    missing: .nan
    monotone_constraints: null
    multi_strategy: null
    n_estimators: 150
    n_jobs: null
    num_parallel_tree: null
    objective: reg:squarederror
    random_state: null
    reg_alpha: null
    reg_lambda: null
    sampling_method: null
    scale_pos_weight: null
    subsample: null
    tree_method: null
    validate_parameters: null
    verbosity: null
  r2_score: 0.9954456278436161
  target_variable: emissions_quantity
